Web/GameShop.Web/Controllers/CartController.cs
namespace GameShop.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using GameShop.Data.Models;
    using GameShop.Services.Data;
    using GameShop.Web.Helpers;
    using GameShop.Web.ViewModels.Game;
    using Microsoft.AspNetCore.Mvc;

    public class CartController : BaseController
    {
        private readonly IGameService gameService;

        public CartController(IGameService gameService)
        {
            this.gameService = gameService;
        }

        public IActionResult Index()
        {
            try
            {

                var cart = SessionHelper.GetObjectFromJson<List<CartItem>>(this.HttpContext.Session, "cart");
                this.ViewBag.cart = cart;
                this.ViewBag.Count = cart.Count();
                this.ViewBag.quantity = cart.Select(item => item.Quantity);
                this.ViewBag.total = cart.Sum(item => item.Game.Price * item.Quantity);
                this.ViewBag.TotalWithoutVAT = cart.Sum(item => item.Game.Price * item.Quantity) * 0.8M;
                this.ViewBag.GameIds = cart.Select(x => x.GameId);
                return this.View();
            }
            catch
            {
                this.TempData["ErrorMessage"] = "Shopping cart is empty";
                this.TempData["InfoMessage"] = null;
                return this.Redirect("/Home/Index");

            }
        }

        [Route("buy/{id}")]
        public IActionResult Buy(string id)
        {
            var game = this.gameService.GetGameById(id);
            var gameModel = new GameViewModel();
            Microsoft.AspNetCore.Http.HttpContext httpContext = this.HttpContext;
            if (SessionHelper.GetObjectFromJson<List<CartItem>>(httpContext.Session, "cart") == null)
            {
                List<CartItem> cart = new List<CartItem>();
                cart.Add(new CartItem { Game = game, Quantity = 1 });
                SessionHelper.SetObjectAsJson(this.HttpContext.Session, "cart", cart);
            }
            else
            {
                List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(httpContext.Session, "cart");
                int index = this.isExist(id);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new CartItem { Game = game, Quantity = 1 });
                }

                SessionHelper.SetObjectAsJson(httpContext.Session, "cart", cart);
            }

            return this.RedirectToAction("Index");
        }

        [Route("remove/{id}")]
        public IActionResult Remove(string id)
        {
            Microsoft.AspNetCore.Http.HttpContext httpContext = this.HttpContext;
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(httpContext.Session, "cart");
            int index = this.isExist(id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(this.HttpContext.Session, "cart", cart);
            return this.RedirectToAction("Index");
        }

        private int isExist(string id)
        {
            Microsoft.AspNetCore.Http.HttpContext httpContext = this.HttpContext;
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(httpContext.Session, "cart");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Game.Id.Equals(id))
                {
                    return i;
                }
            }

            return -1;
        }

    }
}

Web/GameShop.Web/Controllers/GameController.cs
namespace GameShop.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;
    using GameShop.Data.Models;
    using GameShop.Services.Data;
    using GameShop.Web.Helpers;
    using GameShop.Web.ViewModels.Game;
    using Microsoft.AspNetCore.Mvc;

    public class GameController : BaseController
    {
        private readonly IGameService gameService;

        public GameController(IGameService gameService)
        {
            this.gameService = gameService;
        }

        public IActionResult Details(string id)
        {

            var viewModel = this.gameService.GetJobById<GameViewModel>(id);

            return this.View(viewModel);
        }

        public IActionResult BuyGame(string id)
        {
            try
            {
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                this.gameService.BuyGame(id, userId);
                this.TempData["InfoMessage"] = "Успешна покупка";
            }
            catch (Exception e)
            {
                this.TempData["ErrorMessage"] = e.Message;
                this.TempData["InfoMessage"] = null;
            }

            return this.Redirect("/Home/Index");

        }

        public IActionResult BuyGames()
        {
            var cart = SessionHelper.GetObjectFromJson<List<CartItem>>(this.HttpContext.Session, "cart");
            foreach (var game in cart)
            {
                try
                {
                    var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                    this.gameService.BuyGame(game.Game.Id, userId);
                }
                catch (Exception e)
                {
                    this.TempData["ErrorMessage"] = e.Message;
                    this.TempData["InfoMessage"] = null;
                }

            }

            this.HttpContext.Session.Clear();

            return this.Redirect("/Home/Index");

        }

        public IActionResult Buy(string id)
        {
            var game = this.gameService.GetGameById(id);
            var gameModel = new GameViewModel();
            if (SessionHelper.GetObjectFromJson<List<CartItem>>(this.HttpContext.Session, "cart") == null)
            {
                List<CartItem> cart = new List<CartItem>();
                cart.Add(new CartItem { Game = game, Quantity = 1 });
                SessionHelper.SetObjectAsJson(this.HttpContext.Session, "cart", cart);
            }
            else
            {
                List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(this.HttpContext.Session, "cart");
                int index = this.isExist(id);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new CartItem { Game = game, Quantity = 1 });
                }

                SessionHelper.SetObjectAsJson(this.HttpContext.Session, "cart", cart);
            }

            this.TempData["InfoMessage"] = "Добавихте успешно тази игра ";
            return this.Redirect("/Home/Index");
        }

        private int isExist(string id)
        {
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(this.HttpContext.Session, "cart");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Game.Id.Equals(id))
                {
                    return i;
                }
            }
            return -1;
        }
    }
}

Web/GameShop.Web/Views/Cart/Index.cshtml
<!--Section: Block Content-->

<section>

    <!--Grid row-->
    <div class="row">

        <!--Grid column-->
        <div class="col-lg-8">

            <!-- Card -->
            <div class="mb-3">
                <div class="pt-4 wish-list">

                    <h5 class="mb-4">Cart (<span>@ViewBag.Count</span> items)</h5>

                    @foreach (var item in ViewBag.cart)
                    {


                        <div class="row mb-4">
                            <div class="col-md-5 col-lg-3 col-xl-3">
                                <div class="view zoom overlay z-depth-1 rounded mb-3 mb-md-0">
                                    <img class="img-fluid w-100"
                                         src="@item.Game.ImageURL" alt="Sample">
                                    <a href="#!">

                                    </a>
                                </div>
                            </div>
                            <div class="col-md-7 col-lg-9 col-xl-9">
                                <div>
                                    <div class="d-flex justify-content-between">
                                        <div>
                                            <h5>@item.Game.Title</h5>
                                            <p class="mb-3 text-muted text-uppercase small">Price - @item.Game.Price</p>
                                            <p class="mb-2 text-muted text-uppercase small">RealeaseDate: @((item.Game.RealaseDate).Year)</p>
                                            <p class="mb-2 text-muted text-uppercase small">Quantity: @item.Quantity</p>
                                        </div>
                                    </div>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div>
                                            <a class="btn btn-danger" asp-controller="Cart" asp-action="Remove" asp-route-id="@item.Game.Id">
                                                <i class="fas fa-trash-alt mr-1"></i> Remove item
                                            </a>
                                            <a href="#!" type="button" class="card-link-secondary small text-uppercase">
                                                <i class="fas fa-heart mr-1"></i> Move to wish list
                                            </a>
                                        </div>
                                        <p class="mb-0"><span><strong id="summary">@(item.Game.Price)</strong></span></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr class="mb-4">
                    }

                    <p class="text-primary mb-0">
                        <i class="fas fa-info-circle mr-1"></i> Do not delay the purchase, adding
                        items to your cart does not mean booking them.
                    </p>

                </div>
            </div>
            <!-- Card -->
            <!-- Card -->
            <div class="mb-3">
                <div class="pt-4">

                    <h5 class="mb-4">Expected shipping delivery</h5>

                    <p class="mb-0"> @DateTime.UtcNow.AddDays(3)</p>
                </div>
            </div>
            <!-- Card -->
            <!-- Card -->
            <div class="mb-3">
                <div class="pt-4">

                    <h5 class="mb-4">We accept</h5>

                    <img class="mr-2" width="45px"
                         src="https://mdbootstrap.com/wp-content/plugins/woocommerce-gateway-stripe/assets/images/visa.svg"
                         alt="Visa">
                    <img class="mr-2" width="45px"
                         src="https://mdbootstrap.com/wp-content/plugins/woocommerce-gateway-stripe/assets/images/amex.svg"
                         alt="American Express">
                    <img class="mr-2" width="45px"
                         src="https://mdbootstrap.com/wp-content/plugins/woocommerce-gateway-stripe/assets/images/mastercard.svg"
                         alt="Mastercard">
                    <img class="mr-2" width="45px"
                         src="https://mdbootstrap.com/wp-content/plugins/woocommerce/includes/gateways/paypal/assets/images/paypal.png"
                         alt="PayPal acceptance mark">
                </div>
            </div>
            <!-- Card -->

        </div>
        <!--Grid column-->
        <!--Grid column-->
        <div class="col-lg-4">

            <!-- Card -->
            <div class="mb-3">
                <div class="pt-4">

                    <h5 class="mb-3">The total amount of</h5>

                    <ul class="list-group list-group-flush">
                        <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">

                            Temporary amount
                            <span>$@Math.Round(ViewBag.TotalWithoutVAT, 2)</span>

                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                            Shipping
                            <span>Gratis</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                            <div>
                                <strong>The total amount of</strong>
                                <strong>
                                    <p class="mb-0">(including VAT)</p>
                                </strong>
                            </div><strong>$@Math.Round(ViewBag.total, 2)</strong>
                        </li>
                    </ul>
                    @if (this.User.Identity.IsAuthenticated)
                    {

                        <a  asp-controller="Game" asp-action="BuyGames" class="btn btn-primary btn-block" title="Трябва да си регистриран за да продължиш">Check out</a>

                    }
                    else
                    {
                        <a asp-area="Identity" asp-controller="Account" asp-action="Login" class="btn btn-primary btn-block" title="Трябва да си регистриран за да продължиш">Go to check out</a>

                    }

                </div>
            </div>
            <!-- Card -->
            <!-- Card -->
            <div class="mb-3">
                <div class="pt-4">

                    <a class="dark-grey-text d-flex justify-content-between" data-toggle="collapse" href="#collapseExample"
                       aria-expanded="false" aria-controls="collapseExample">
                        Add a discount code (optional)
                        <span><i class="fas fa-chevron-down pt-1"></i></span>
                    </a>

                    <div class="collapse" id="collapseExample">
                        <div class="mt-3">
                            <div class="md-form md-outline mb-0">
                                <input type="text" id="discount-code" class="form-control font-weight-light"
                                       placeholder="Enter discount code">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Card -->

        </div>
        <!--Grid column-->

    </div>
    <!-- Grid row -->

</section>
<!--Section: Block Content-->