Web/GameShop.Web/Areas/Administration/Controllers/DashboardController.cs
namespace GameShop.Web.Areas.Administration.Controllers
{
    using System.Threading.Tasks;

    using GameShop.Services.Data;
    using GameShop.Web.ViewModels.Administration.Dashboard;
    using GameShop.Web.ViewModels.Game;
    using Microsoft.AspNetCore.Mvc;

    public class DashboardController : AdministrationController
    {
        private readonly IGameService gameService;

        public DashboardController(IGameService gameService)
        {
            this.gameService = gameService;
        }

        public IActionResult Index()
        {
            return this.View();
        }

        public IActionResult CreateGame()
        {
            return this.View("Game/CreateGame");
        }

        [HttpPost]
        public async Task<ActionResult> CreateGame(GameViewModel model)
        {
            await this.gameService.CreateAsync(model.Title, model.Description, model.ImageURL, model.Price, model.RealaseDate);
            return this.RedirectToAction("Index");
        }

        public IActionResult EditGame()
        {
            return this.View("Game/EditGame");
        }

        [HttpPost]
        public async Task<ActionResult> EditGame(GameViewModel model)
        {
            await this.gameService.EditAsync(model.Id, model.Title, model.Description, model.ImageURL, model.Price);
            return this.Redirect("/Administration/Dashboard");
        }

        public async Task<ActionResult> Delete(string id)
        {
            await this.gameService.DeleteAsync(id);
            return this.RedirectToAction("Index");
        }
    }
}

Web/GameShop.Web/Controllers/GameController.cs
namespace GameShop.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;
    using GameShop.Data.Models;
    using GameShop.Services.Data;
    using GameShop.Web.Helpers;
    using GameShop.Web.ViewModels.Game;
    using Microsoft.AspNetCore.Mvc;

    public class GameController : BaseController
    {
        private readonly IGameService gameService;

        public GameController(IGameService gameService)
        {
            this.gameService = gameService;
        }

        public IActionResult Details(string id)
        {

            var viewModel = this.gameService.GetJobById<GameViewModel>(id);

            return this.View(viewModel);
        }

        public IActionResult BuyGame(string id)
        {
            try
            {
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                this.gameService.BuyGame(id, userId);
                this.TempData["InfoMessage"] = "Успешна покупка";
            }
            catch (Exception e)
            {
                this.TempData["ErrorMessage"] = e.Message;
                this.TempData["InfoMessage"] = null;
            }

            return this.Redirect("/Home/Index");

        }

        public IActionResult BuyGames()
        {
            var cart = SessionHelper.GetObjectFromJson<List<CartItem>>(this.HttpContext.Session, "cart");
            foreach (var game in cart)
            {
                try
                {
                    var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                    this.gameService.BuyGame(game.Game.Id, userId);
                }
                catch (Exception e)
                {
                    this.TempData["ErrorMessage"] = e.Message;
                    this.TempData["InfoMessage"] = null;
                }

            }

            this.HttpContext.Session.Clear();

            return this.Redirect("/Home/Index");

        }

        public IActionResult Buy(string id)
        {
            var game = this.gameService.GetGameById(id);
            var gameModel = new GameViewModel();
            if (SessionHelper.GetObjectFromJson<List<CartItem>>(this.HttpContext.Session, "cart") == null)
            {
                List<CartItem> cart = new List<CartItem>();
                cart.Add(new CartItem { Game = game, Quantity = 1 });
                SessionHelper.SetObjectAsJson(this.HttpContext.Session, "cart", cart);
            }
            else
            {
                List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(this.HttpContext.Session, "cart");
                int index = this.isExist(id);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new CartItem { Game = game, Quantity = 1 });
                }

                SessionHelper.SetObjectAsJson(this.HttpContext.Session, "cart", cart);
            }

            this.TempData["InfoMessage"] = "Добавихте успешно тази игра ";
            return this.Redirect("/Home/Index");
        }

        private int isExist(string id)
        {
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(this.HttpContext.Session, "cart");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Game.Id.Equals(id))
                {
                    return i;
                }
            }
            return -1;
        }
    }
}

Web/GameShop.Web/Controllers/HomeController.cs
namespace GameShop.Web.Controllers
{
    using System.Diagnostics;
    using System.Linq;

    using GameShop.Services.Data;
    using GameShop.Web.ViewModels;
    using GameShop.Web.ViewModels.Game;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.CodeAnalysis.CSharp.Syntax;
    using Newtonsoft.Json;

    public class HomeController : BaseController
    {
        private readonly IGameService gameService;

        public HomeController(IGameService gameService)
        {
            this.gameService = gameService;
        }

        public IActionResult Index(int page = 1, string searchString = null)
        {
            this.ViewData["CurrentFilter"] = searchString;
            if (!string.IsNullOrEmpty(searchString))
            {
                var viewModel = new AllGamesViewModel
                {
                    Games = this.gameService.GetAll<GameViewModel>().Where(x
                        => x.Title.ToLower().Contains(searchString.ToLower()) || x.Title.ToLower().Contains(searchString.ToLower())),
                };
                if (viewModel.Games.Any())
                {
                    return this.View(viewModel);

                }

                this.TempData["ErrorMessage"] = "Error";
                this.TempData["InfoMessage"] = null;
            }

            var view = new AllGamesViewModel
            {
                Games = this.gameService.GetAll<GameViewModel>(),
            };

            return this.View(view);
        }

        public IActionResult Privacy()
        {
            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(
                new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }
    }
}

Web/GameShop.Web/Views/Home/Index.cshtml
@using Microsoft.CodeAnalysis.CSharp.Syntax
@using GameShop.Common
@model GameShop.Web.ViewModels.Game.AllGamesViewModel
<!--Section: Block Content-->
<!--Section: Block Content-->


@if (this.TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        @this.TempData["ErrorMessage"]
    </div>
}
@if (this.TempData["InfoMessage"] != null)
{
    <div class="alert alert-success">
        @this.TempData["InfoMessage"]
    </div>
}

<section>
    @foreach (var game in Model.Games)
    {


        <div class="row mb-4">
            <div class="col-md-5 col-lg-3 col-xl-3">

                <div class="view zoom overlay z-depth-1 rounded mb-3 mb-md-0">
                    <a href= "/Game/Details/@game.Id">
                        <img class="img-fluid w-100"
                             src="@game.ImageURL"
                             alt="Sample"
                             width="80" height="80">

                    </a>
                </div>

            </div>
            <div class="col-md-7 col-lg-9 col-xl-9">
                <div class="row">
                    <div class="col-lg-7 col-xl-7">

                        <h5>@game.Title</h5>
                        <p class="mb-2 text-muted text-uppercase small">YEAR: @game.RealaseDate.Year</p>

                        <hr>
                        <p class="mb-lg-0">
                            @game.Description
                        </p>

                    </div>
                    <div class="col-lg-5 col-xl-5">

                        <h6 class="mb-3"><span>$@game.Price</span></h6>
                        <div class="my-4">
                            <a asp-controller="Game" asp-action="Buy" asp-route-id="@game.Id"
                               type="button" class="btn btn-primary btn-md mr-1 mb-2">
                                <i class="fas fa-shopping-cart pr-2"></i>Add to cart

                            </a>

                            <a asp-controller="Game" asp-action="Details" asp-route-id="@game.Id" type="button" class="btn btn-light btn-md mr-1 mb-2">
                                <i class="fas fa-info-circle pr-2"></i>Details

                            </a>
                        </div>
                        @*<a asp-controller="Game" asp-action="Buy" asp-route-id="@game.Id"
                           type="button" class="btn btn-danger btn-md px-3 mb-lg-2 material-tooltip-main"
                           data-toggle="tooltip" data-placement="top" title="Add to wishlist">
                            <i class="far fa-heart"></i>

                        </a>*@

                        @if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
                        {
                            <a asp-are="Admin" asp-controller="Dashboard" asp-action="Delete" asp-route-id="@game.Id"
                               type="button" class="btn btn-danger btn-md px-3 mb-lg-2 material-tooltip-main"
                               data-toggle="tooltip" data-placement="top" title="Delete">
                                <i class="fas fa-trash-alt"></i>

                            </a>
                        }

                    </div>
                </div>
            </div>
        </div>
        <hr />
    }
</section>
<!--Section: Block Content-->


<script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
<script>
    $(".btn-danger").click(function (e) {
        if (confirm("Are you sure?")) {
            alert('OK');
        }
        else {
            e.preventDefault();
        }
    });
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script>
    $('th').click(function () {
        var table = $(this).parents('table').eq(0)
        var rows = table.find('tr:gt(0)').toArray().sort(comparer($(this).index()))
        this.asc = !this.asc
        if (!this.asc) { rows = rows.reverse() }
        for (var i = 0; i < rows.length; i++) { table.append(rows[i]) }
    })
    function comparer(index) {
        return function (a, b) {
            var valA = getCellValue(a, index), valB = getCellValue(b, index)
            return $.isNumeric(valA) && $.isNumeric(valB) ? valA - valB : valA.toString().localeCompare(valB)
        }
    }
    function getCellValue(row, index) { return $(row).children('td').eq(index).text() }
</script>